sudo: required
language: generic


services:
  - docker

before_install:
  - docker build -t cklins/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true cklins/docker-react npm run test