sudo: required
language: generic


services:
  - docker

before_install:
  - docker build -t cklins/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true cklins/docker-react npm run test


deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "cklin"
  env: "Cklin-env"
  bucket_name: "elasticbeanstalk-ap-northeast-1-131855297103"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY  